name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.0.2
      with:
        ndk-version: r21d
    - name: Debug
      run: which ndk-build
#    - name: Build
#      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
#    - name: Upload
#      uses: actions/upload-artifact@v2
#      with:
#        name: libs
#        path: libs/
