name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/ndk/r21d/x64
        key: ${{ runner.os }}-android-ndk-r21d
    - name: Setup Android NDK
      if: steps.cache.outputs.cache-hit != 'true'
      uses: nttld/setup-ndk@v1.0.2
      with:
        ndk-version: r21d
    - name: Build
      run: |
            export PATH=$PATH:/opt/hostedtoolcache/ndk/r21d/x64
            ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: libs
        path: libs/
